Propose support for `withinPolygon` query constraint
parse-server-modules/parse-evolution pull request #4
Opened 2017-01-21 14:40 UTC by madsb

2017-01-21 17:01 UTC, tarekskr commented
Awesome! Thank you @madsb !

2017-01-21 17:32 UTC, flovilmart requested changes

2017-01-21 17:32 UTC, flovilmart commented on proposals/0002-within-polygon.md
> +Introducing a `withinPolygon` constraint that takes an array of lat/lon coordinates, or even nested arrays of coordinates for MultiPolygon support.
Can you expand on that and describe with the JSON payloads how it should look like?

2017-02-02 08:54 UTC, madsb commented
I've expanded a bit - does it suffice?

2022-02-11 06:17 UTC, closed without merging